#!/bin/bash
#
# Autor Original: Alex S.
# https://www.youtube.com/channel/UCrE7Vzc6G971XnrDyo53mGA
#
# Controlar Limite do clock da CPU

INFO_CPU_MODEL_NAME=$(sed 's/^.*: //' <(grep -m1 -i 'model name' /proc/cpuinfo))
INFO_CPU_CLOCK_MIN=$(sort -u /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_min_freq)
INFO_CPU_CLOCK_BASE=$(sort -u /sys/devices/system/cpu/cpu*/cpufreq/base_frequency)
INFO_CPU_CLOCK_MAX=$(sort -u /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq)
INFO_CPU_CLOCK_MAX_SET=$(sort -u /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq)

ZENITY_TITLE=$(
	echo $INFO_CPU_MODEL_NAME
	sed 's/...$/ MHz/' <<< "Clock Mínimo: $INFO_CPU_CLOCK_MIN"
	sed 's/...$/ MHz/' <<< "Clock Base: $INFO_CPU_CLOCK_BASE"
	sed 's/...$/ MHz/' <<< "Clock Máximo: $INFO_CPU_CLOCK_MAX" 
)

ZENITY_SELECT_CLOCK_MAX=$(
	zenity \
		--window-icon="/usr/share/icons/Adwaita/256x256/legacy/system-run.png" \
		--title='Frequência Limite da CPU v1.1' \
		--cancel-label="Sair" \
		--ok-label="Aplicar" \
		--text="<span size=\"large\">$ZENITY_TITLE</span>"\
		--scale \
		--min-value=$INFO_CPU_CLOCK_MIN \
		--value=$INFO_CPU_CLOCK_MAX_SET \
		--max-value=$INFO_CPU_CLOCK_MAX \
		--step=100000
) && pkexec sh -c "sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq <<< '$ZENITY_SELECT_CLOCK_MAX'" && sh -c "'$0'"
