#!/bin/bash
#
# Autor Original: Alex S.
# https://www.youtube.com/channel/UCrE7Vzc6G971XnrDyo53mGA
#
# Controlar Limite do clock da CPU


CPU_CLOCK_MAX_FOLDER=~/.config/cpu-limit
CPU_CLOCK_MAX_FILE="$CPU_CLOCK_MAX_FOLDER/cpu-max"

CPU_MODEL_NAME="$(sed 's/^.*: //' <(grep -m1 -i 'model name' /proc/cpuinfo))"
CPU_CORES="$(grep -Eo [[:digit:]] <(grep -m1 -i "cpu cores" /proc/cpuinfo))"
CPU_THREADS="$(nproc --all)"

CPU_CLOCK_MIN="$(sort -u /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_min_freq)"
CPU_CLOCK_BASE="$(sort -u /sys/devices/system/cpu/cpu*/cpufreq/base_frequency)"
CPU_CLOCK_SET="$(sort -u /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq)"


# Aqui possui um bug na hora do sistema pegar a frequência máxima da cpu, às vezes
# ele pega a frequência base como frequência máxima se você não redefinir a
# frequência que você alterou, então eu guardo o valor na primeira inicialização
# da aplicação em um arquivo para servir como referência.
[ -e "$CPU_CLOCK_MAX_FILE" ] && {
	echo "DEBUG: Usando frequência máxima do cache."
	CPU_CLOCK_MAX="$(< "$CPU_CLOCK_MAX_FILE")"
} || {
	echo "DEBUG: Usando frequência máxima do sistema."
	CPU_CLOCK_MAX="$(sort -u /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq)"
	[ ! -e "$CPU_CLOCK_MAX_FOLDER" ] && mkdir -p "$CPU_CLOCK_MAX_FOLDER"
	echo "$CPU_CLOCK_MAX" > "$CPU_CLOCK_MAX_FILE"
}


TITLE=$(
	echo "$CPU_MODEL_NAME \nNúcleos: $CPU_CORES\tThreads: $CPU_THREADS\n"
	sed 's/...$/ MHz/' <<< "Clock Mínimo: $CPU_CLOCK_MIN"
	sed 's/...$/ MHz/' <<< "Clock Base: $CPU_CLOCK_BASE"
	sed 's/...$/ MHz/' <<< "Clock Máximo: $CPU_CLOCK_MAX"
)


SELECT_CLOCK_MAX=$(
	zenity \
		--window-icon="/usr/share/icons/Adwaita/256x256/legacy/system-run.png" \
		--title='Frequência Limite da CPU v2.0' \
		--cancel-label="Sair" \
		--ok-label="Aplicar" \
		--text="<span size=\"large\">$TITLE</span>"\
		--scale \
		--min-value=$CPU_CLOCK_MIN \
		--value=$CPU_CLOCK_SET \
		--max-value=$CPU_CLOCK_MAX \
		--step=100000
) && pkexec sh -c "sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq <<< '$SELECT_CLOCK_MAX'" && sh -c "'$0'"
